apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
resources:
  - ../../base/echosrv/echosrv
metadata:
  name: echosrv
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: echosrv
  targetNamespace: echosrv