apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: echo-server
  namespace: echo-server
spec:
  chart:
    spec:
      version: "0.3.1"
  values:
    ingress:
      hosts:
        - host: echo-server.lcwdev.com
          paths:
            - path: /
              pathType: ImplementationSpecific
